// src/navigation/index.jsx or wherever you're putting it
import { ChartColumn, ChartNoAxesColumnIncreasing, Home, NotepadText, Package, PackagePlus, Settings, LogOut } from "lucide-react";
import profile from '../assets/profile.png'



export const navbarLinks = [
  {
    title: "Dashboard",
    links: [
      {
        label: "Dashboard",
        icon: Home,
        path: "/Dashboard",
      },
      {
        label: "Elections",
        icon: NotepadText,
        path: "/Dashboard/Elections",
      },
      {
        label: "Candidates",
        icon: ChartColumn,
        path: "/Dashboard/Candidates",
      },
      {
        label: "Reports",
        icon: NotepadText,
        path: "/reports",
      },
    ],
  },
  {
    title: "Results",
    links: [
      {
        label: "Stock",
        icon: Package,
        path: "/stock",
      },
      {
        label: "New Item",
        icon: PackagePlus,
        path: "/items/new",
      },
    ],
  },
  {
    title: "Settings",
    links: [
      {
        label: "Preferences",
        icon: Settings,
        path: "/settings",
      },

      {
        label: "Logout",
        icon: LogOut,
        path: "/Logout",
      },
    ],
  },
];

export const OverviewData = [
  { name: "Jan", total: 999 },
  { name: "Feb", total: 820 },
  { name: "Mar", total: 1060 },
  { name: "Apr", total: 940 },
  { name: "May", total: 1125 },
  { name: "Jun", total: 1032 },
  { name: "Jul", total: 980 },
  { name: "Aug", total: 1167 },
  { name: "Sep", total: 1015 },
  { name: "Oct", total: 1230 },
  { name: "Nov", total: 1095 },
  { name: "Dec", total: 990 },
];

export const Candidates = [
  {
    id: 1,
    name: "Olivia Martin",
    email: "olivia.martin@gmail.com",
    image: profile,
    total: 1500,
  },
   {
    id: 2,
    name: "Liam Johnson",
    email: "liam.johnson@gmail.com",
    image: profile,
    total: 1380,
  },
  {
    id: 3,
    name: "Emma Davis",
    email: "emma.davis@gmail.com",
    image: profile,
    total: 1455,
  },
  {
    id: 4,
    name: "Noah Wilson",
    email: "noah.wilson@gmail.com",
    image: profile,
    total: 1302,
  },
  {
    id: 5,
    name: "Ava Thompson",
    email: "ava.thompson@gmail.com",
    image: profile,
    total: 1601,
  },
  {
    id: 6,
    name: "William Garcia",
    email: "william.garcia@gmail.com",
    image: profile,
    total: 1224,
  },
  {
    id: 7,
    name: "Sophia Martinez",
    email: "sophia.martinez@gmail.com",
    image: profile,
    total: 1423,
  },
  {
    id: 8,
    name: "James Anderson",
    email: "james.anderson@gmail.com",
    image: profile,
    total: 1359,
  },
  {
    id: 9,
    name: "Isabella Taylor",
    email: "isabella.taylor@gmail.com",
    image: profile,
    total: 1480,
  },
  {
    id: 10,
    name: "Benjamin Moore",
    email: "benjamin.moore@gmail.com",
    image: profile,
    total: 1555,
  },
  {
    id: 11,
    name: "Mia Jackson",
    email: "mia.jackson@gmail.com",
    image: profile,
    total: 1270,
  }
]

export const registeredVoters = [
  {
    id: 1,
    firstName: "Olivia",
    lastName: "Martin",
    gender: "Female",
    dateOfBirth: "1995-04-12",
    nationalId: "MW12345678",
    email: "olivia.martin@example.com",
    phone: "+265881234567",
    address: "Area 18, Lilongwe",
    region: "Central",
    constituency: "Lilongwe City South",
    registrationCenter: "Area 18 Primary School",
    registrationDate: "2025-01-10",
    isActive: true,
    profileImage: profile, // or import if needed
  },
  {
    id: 2,
    firstName: "James",
    lastName: "Phiri",
    gender: "Male",
    dateOfBirth: "1988-09-20",
    nationalId: "MW98765432",
    email: "james.phiri@example.com",
    phone: "+265992345678",
    address: "Zingwangwa, Blantyre",
    region: "Southern",
    constituency: "Blantyre City East",
    registrationCenter: "Zingwangwa Secondary School",
    registrationDate: "2025-01-15",
    isActive: true,
    profileImage: profile,
  },
  {
    id: 3,
    firstName: "Aisha",
    lastName: "Chikondi",
    gender: "Female",
    dateOfBirth: "1999-07-08",
    nationalId: "MW45678901",
    email: "aisha.chikondi@example.com",
    phone: "+265993456789",
    address: "Mchengautuba, Mzuzu",
    region: "Northern",
    constituency: "Mzuzu City West",
    registrationCenter: "Mzuzu Government School",
    registrationDate: "2025-02-02",
    isActive: false,
    profileImage: profile,
  },
  {
    id: 4,
    firstName: "Blessings",
    lastName: "Kumwenda",
    gender: "Male",
    dateOfBirth: "1993-11-02",
    nationalId: "MW22334455",
    email: "blessings.kumwenda@example.com",
    phone: "+265994567890",
    address: "Area 25, Lilongwe",
    region: "Central",
    constituency: "Lilongwe North",
    registrationCenter: "Area 25B School",
    registrationDate: "2025-02-10",
    isActive: true,
    profileImage: profile,
  },
  {
    id: 5,
    firstName: "Thokozani",
    lastName: "Msowoya",
    gender: "Non-Binary",
    dateOfBirth: "2000-03-18",
    nationalId: "MW66778899",
    email: "thokozani.msowoya@example.com",
    phone: "+265995678901",
    address: "Likoma Island",
    region: "Northern",
    constituency: "Likoma Islands",
    registrationCenter: "Likoma Community Center",
    registrationDate: "2025-03-01",
    isActive: false,
    profileImage: profile,
  },

  {
    id: 6,
    firstName: "Thokozani",
    lastName: "Msowoya",
    gender: "Non-Binary",
    dateOfBirth: "2000-03-18",
    nationalId: "MW66778899",
    email: "thokozani.msowoya@example.com",
    phone: "+265995678901",
    address: "Likoma Island",
    region: "Northern",
    constituency: "Likoma Islands",
    registrationCenter: "Likoma Community Center",
    registrationDate: "2025-03-01",
    isActive: false,
    profileImage: profile,
  },

  {
    id:7 ,
    firstName: "Thokozani",
    lastName: "Msowoya",
    gender: "Non-Binary",
    dateOfBirth: "2000-03-18",
    nationalId: "MW66778899",
    email: "thokozani.msowoya@example.com",
    phone: "+265995678901",
    address: "Likoma Island",
    region: "Northern",
    constituency: "Likoma Islands",
    registrationCenter: "Likoma Community Center",
    registrationDate: "2025-03-01",
    isActive: false,
    profileImage: profile,
  }
];
